udp:
  ip: 192.168.2.100
  port: 8000
  serverport: 5551
humanset:
  bodyfile: body_unity_pose
  targethandfile: human_hand_info
system:
  usecan: false
  usegui: false
  usenetpub: false
  useudp: true
  useudpserver: true
  usesapien: true
  sapientype: right
  can:
    id: 40
    bitrate: 1000000
    dofs: 25
  robotname_r: l10
  robotname_l: l10
  retargeting_type: projection
  datasource_type: motion
  motion_type: udexreal
  motion_device: ycc
  rightpub: true
  leftpub: true
debug:
  joint_pub_debug: false
  joint_motor_debug_r: true
  joint_motor_debug_l: true
netpub:
  ip: 192.168.11.33
  port: 20008
